printWidth: 150
tabWidth: 2
semi: true
singleQuote: true
trailingComma: 'none'
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: 'always'
svelteSortOrder: styles-scripts-markup
svelteStrictMode: true
svelteBracketNewLine: true
svelteAllowShorthand: false
